export const SET_IDENTITY_TO_PROVISION_FIELD = "SET_IDENTITY_TO_PROVISION_FIELD";
export const SET_PROVISONING_INFO = "SET_PROVISONING_INFO";
export const SET_PROVISONING_RESPONSE = "SET_PROVISONING_RESPONSE";
export const SET_REQUESTED_FQN = "SET_REQUESTED_FQN";
export const SET_REQUESTED_ID = "SET_REQUESTED_ID";
export const SET_PROVISONING_NAME = "SET_PROVISONING_NAME";